dbDEV:
  image: million12/mariadb:latest
  ports:
    - 3306
  environment:
    MARIADB_PASS: devsecretpassw

webDEV:
  image: weissheiten/base-neos-distribution
  ports:
    - '8080:80'
  links:
    - dbDEV:db
  environment:
    T3APP_VHOST_NAMES: 'neos dev.neos behat.dev.neos'
    T3APP_NEOS_SITE_PACKAGE: 'Billardcafe.Home'
    T3APP_NEOS_SITE_PACKAGE_FORCE_REIMPORT: 'false'

devDEV:
  image: million12/php-app-ssh
  ports:
    - '1122:22'
  links:
    - dbDEV:db
    - webDEV:web
  volumes_from:
    - webDEV
  environment:
    IMPORT_GITHUB_PUB_KEYS: weissheiten
