129dbdataDEV:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /home/florian/DockerSetups/NeosDev129/lib/mysql:/var/lib/mysql

129dbDEV:
  image: tutum/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - 129dbdataDEV
  environment:
    MARIADB_PASS: spassw

129webdataDEV:
  image: busybox:latest
  command: echo 129webdataDEV
  volumes:
    - /home/florian/DockerSetups/NeosDev129/data:/data

129webDEV:
  image: weissheiten/base-neos-distribution-1p2p9
  ports:
    - '8080:80'
  links:
    - 129dbDEV:db
  volumes_from:
    - 129webdataDEV
  environment:
    T3APP_VHOST_NAMES: 'neos dev.neos behat.dev.neos'
    T3APP_NEOS_SITE_PACKAGE: 'Billardcafe.Home'
    T3APP_NEOS_SITE_PACKAGE_FORCE_REIMPORT: 'false'

129devDEV:
  image: million12/php-app-ssh
  ports:
    - '1122:22'
  links:
    - 129dbDEV:db
    - 129webDEV:web
  volumes_from:
    - 129webDEV
  environment:
    IMPORT_GITHUB_PUB_KEYS: weissheiten
