dbdataDEV:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /home/florian/DockerSetups/NeosDev/lib/mysql:/var/lib/mysql

dbDEV:
  image: tutum/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdataDEV
  environment:
    MARIADB_PASS: spassw

webdataDEV:
  image: busybox:latest
  command: echo webdataDEV
  volumes:
    - /home/florian/DockerSetups/NeosDev/data:/data

webDEV:
  image: weissheiten/base-neos-distribution
  ports:
    - '8080:80'
  links:
    - dbDEV:db
  volumes_from:
    - webdataDEV
  environment:
    T3APP_VHOST_NAMES: 'neos dev.neos behat.dev.neos'
    T3APP_NEOS_SITE_PACKAGE: 'Billardcafe.Home'
    T3APP_NEOS_SITE_PACKAGE_FORCE_REIMPORT: 'false'

devDEV:
  image: million12/php-app-ssh
  ports:
    - '1122:22'
  links:
    - dbDEV:dbDEV
    - webDEV:webDEV
  volumes_from:
    - webDEV
  environment:
    IMPORT_GITHUB_PUB_KEYS: weissheiten
